//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTV.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonTraSach
    {
        public int MaHD { get; set; }
        public System.DateTime NgayLapHD { get; set; }
        public int MaPM { get; set; }
        public decimal TienThanhToan { get; set; }
    
        public virtual PhieuMuon PhieuMuon { get; set; }
    }
}
